spring:
  application:
    name: provider
server:
  port: 8100 # zookeeper端口也会启动8080

dubbo:
  application:
    name: provider

  protocol:
    name: dubbo
    port: 20880

# 消费者不需要注册
#  registry:
#    # 1.直连
#    address: N/A
    # 2.注册中心
    #  ?blockUntilConnectedWait=100000&timeout=100000 不加这个可能会导致连接失败,因为服务器的zookeeper连接有时比较慢
#    address: zookeeper://${zookeeper_host:127.0.0.1}:2181?blockUntilConnectedWait=100000&timeout=100000
#    file:  F:/study/java_study/dubbo-demo/dubboFile/dubbo-cache/${spring.application.name}/dubbo.cache